### ISSUE TITLE
Servidor Intelbras

### ISSUE THREAD

**Issue by joaofidelix** [wschoenell/intelbras_monitor#1]
Olá.
Você sabe me dizer, se na configuração da central de alarme, tem que ter só 1 servidor para enviar os eventos.
Ou posso ter tipo:
Servidor 1: Intelbras
Servidor 2: servidor rodando esse client

E a central de alarme enviaria para os dois.

Pergunto por que hoje configurei desta forma, porém não estou recebendo os eventos no client. Só recebo que a central conectou ao client. Mas nenhum evento depois. De Ativação, Desativação...

E parabéns pelo projeto.

**Comment by wschoenell** [comment]
Opa... era assim mesmo que eu usava. será que eles atualizaram o protocolo? tem como tentar usar esse código como servidor principal para testar?

Tenta descomentar essa linha https://github.com/wschoenell/intelbras_monitor/blob/main/socket_server.py#L21

**Comment by joaofidelix** [comment]
Sim, acho que mudaram o protocolo.

`Connected (<socket.socket fd=8, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('192.168.15.21', 9009), raddr=('192.168.15.23', 1355)>, ('192.168.15.23', 1355))
Received: 07944500005a0299e9
b'07c458108c5a029938'
MAC ADDR: 58108c5a0298
b'\x11'
data: 11b0110a0a0a0a010803040a010a02010a024b
fe`

Quando mudei para o servidor 1, recebi o evento.
Sabe onde posso coseguir ver os protocolos?

**Comment by joaofidelix** [comment]
Achei esse outro projeto, que aparentemente esta decodificando certo:
[https://github.com/elvis-epx/alarme-intelbras](https://github.com/elvis-epx/alarme-intelbras)

**Comment by wschoenell** [comment]
Boa! Acho que aquele lá deve ser mais completo, já que é mais recente :-)
